sudo: false
language: php

php:
    - "hhvm"
    - "hhvm-nightly"

before_script:
    - composer selfupdate
    - composer install --prefer-source
    - bin/findfactories vendor/kilahm/ioc-factory-container-tests/Test/Fixtures/

script:
    - hh_server --check .
    - vendor/bin/hackunit vendor/kilahm/ioc-factory-container-tests/Test
