language: php

php:
    - "hhvm"
    - "hhvm-nightly"

before_script:
    - composer install --prefer-source
    - bin/findfactories Test/Fixtures/

script:
    - hh_client
    - vendor/bin/hackunit Test
